Repository futureleadersupc/waw-backend-json, pull requests merged in 2022-05, with the labels that each got.

#1 chore(sync): initial setup of fake API file sync
  .github/sync.yml
Labels: chore, scope: sync

#3 feat: added fake data for users and projects
  db.json
Labels: enhancement

#5 fix: replace image url
  db.json
Labels: bug

#6 feat: experience and education
  db.json
Labels: enhancement
